version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "pip inst_req"
      prefix-development: "pip ext_req"
      include: "scope"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "ansible"
    labels:
      - "dependencies"
